[2024-04-17T07:29:19.406+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:29:19.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:29:19.413+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:29:19.412+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:29:22.927+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:29:22.910+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 68, in <module>
    python_callable=process_data,
                    ^^^^^^^^^^^^
NameError: name 'process_data' is not defined
[2024-04-17T07:29:22.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:29:22.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 3.572 seconds
[2024-04-17T07:29:53.280+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:29:53.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:29:53.284+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:29:53.283+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:29:54.311+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:29:54.298+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 62, in <module>
    python_callable=load_data_from_postgres,
                    ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'load_data_from_postgres' is not defined. Did you mean: 'write_data_to_postgres'?
[2024-04-17T07:29:54.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:29:54.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.068 seconds
[2024-04-17T07:30:24.595+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:30:24.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:30:24.600+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:30:24.600+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:30:25.959+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:30:25.948+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 62, in <module>
    python_callable=load_data_from_postgres,
                    ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'load_data_from_postgres' is not defined. Did you mean: 'write_data_to_postgres'?
[2024-04-17T07:30:25.966+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:30:25.988+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.400 seconds
[2024-04-17T07:30:51.993+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:30:51.994+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:30:51.997+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:30:51.996+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:30:52.027+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:30:52.025+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 37
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:30:52.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:30:52.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.072 seconds
[2024-04-17T07:31:13.278+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:13.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:31:13.282+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:31:13.282+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:13.304+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:31:13.303+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 37
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:31:13.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:13.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.061 seconds
[2024-04-17T07:31:32.538+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:32.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:31:32.542+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:31:32.542+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:32.565+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:31:32.564+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 37
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:31:32.566+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:32.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.067 seconds
[2024-04-17T07:31:37.588+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:37.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:31:37.592+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:31:37.592+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:37.612+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:31:37.611+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 37
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:31:37.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:37.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.059 seconds
[2024-04-17T07:31:41.685+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:41.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:31:41.698+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:31:41.691+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:41.742+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:31:41.740+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 37
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:31:41.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:41.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.117 seconds
[2024-04-17T07:31:47.768+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:47.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:31:47.773+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:31:47.772+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:47.792+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:31:47.790+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 37
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:31:47.793+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:47.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.059 seconds
[2024-04-17T07:31:57.980+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:57.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:31:57.985+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:31:57.984+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:58.003+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:31:58.002+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 37
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:31:58.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:31:58.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.053 seconds
[2024-04-17T07:32:00.062+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:00.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:32:00.066+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:32:00.066+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:00.087+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:32:00.086+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 37
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:32:00.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:00.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.054 seconds
[2024-04-17T07:32:17.241+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:17.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:32:17.246+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:32:17.245+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:17.264+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:32:17.263+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 44
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:32:17.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:17.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.054 seconds
[2024-04-17T07:32:18.300+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:18.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:32:18.306+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:32:18.306+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:18.334+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:32:18.332+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:32:18.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:18.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.070 seconds
[2024-04-17T07:32:23.388+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:23.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:32:23.393+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:32:23.392+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:23.429+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:32:23.427+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:32:23.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:23.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.079 seconds
[2024-04-17T07:32:53.747+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:53.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:32:53.750+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:32:53.750+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:53.770+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:32:53.768+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:32:53.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:32:53.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.063 seconds
[2024-04-17T07:33:24.105+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:33:24.108+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:33:24.112+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:33:24.111+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:33:24.146+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:33:24.144+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:33:24.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:33:24.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.102 seconds
[2024-04-17T07:33:54.485+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:33:54.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:33:54.489+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:33:54.489+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:33:54.515+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:33:54.513+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:33:54.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:33:54.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.070 seconds
[2024-04-17T07:34:24.897+0000] {processor.py:161} INFO - Started process (PID=128) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:34:24.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:34:24.901+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:34:24.901+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:34:24.932+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:34:24.931+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:34:24.933+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:34:24.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.072 seconds
[2024-04-17T07:34:55.278+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:34:55.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:34:55.282+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:34:55.282+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:34:55.302+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:34:55.300+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:34:55.302+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:34:55.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.056 seconds
[2024-04-17T07:35:25.632+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:35:25.633+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:35:25.637+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:35:25.636+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:35:25.660+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:35:25.658+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:35:25.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:35:25.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.073 seconds
[2024-04-17T07:35:56.015+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:35:56.016+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:35:56.019+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:35:56.018+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:35:56.039+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:35:56.038+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:35:56.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:35:56.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.057 seconds
[2024-04-17T07:36:26.392+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:36:26.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:36:26.396+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:36:26.395+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:36:26.416+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:36:26.415+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:36:26.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:36:26.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.057 seconds
[2024-04-17T07:36:56.760+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:36:56.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:36:56.764+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:36:56.764+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:36:56.796+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:36:56.794+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:36:56.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:36:56.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.075 seconds
[2024-04-17T07:37:27.157+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:37:27.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:37:27.160+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:37:27.160+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:37:27.179+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:37:27.178+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:37:27.180+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:37:27.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.055 seconds
[2024-04-17T07:37:57.520+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:37:57.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:37:57.524+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:37:57.524+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:37:57.546+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:37:57.545+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:37:57.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:37:57.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.063 seconds
[2024-04-17T07:38:27.899+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:38:27.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:38:27.906+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:38:27.905+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:38:27.934+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:38:27.931+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:38:27.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:38:27.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.082 seconds
[2024-04-17T07:38:58.291+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:38:58.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:38:58.295+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:38:58.295+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:38:58.318+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:38:58.317+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:38:58.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:38:58.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.062 seconds
[2024-04-17T07:39:28.735+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:39:28.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:39:28.741+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:39:28.740+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:39:28.763+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:39:28.761+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:39:28.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:39:28.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.060 seconds
[2024-04-17T07:39:59.121+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:39:59.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:39:59.127+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:39:59.127+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:39:59.147+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:39:59.146+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:39:59.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:39:59.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.066 seconds
[2024-04-17T07:40:29.512+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:40:29.513+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:40:29.516+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:40:29.516+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:40:29.542+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:40:29.541+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:40:29.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:40:29.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.064 seconds
[2024-04-17T07:40:59.873+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:40:59.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:40:59.878+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:40:59.877+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:40:59.902+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:40:59.901+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:40:59.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:40:59.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.064 seconds
[2024-04-17T07:41:30.251+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:41:30.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:41:30.255+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:41:30.254+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:41:30.275+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:41:30.274+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 43
    sales_fact = 
                 ^
SyntaxError: invalid syntax
[2024-04-17T07:41:30.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:41:30.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.072 seconds
[2024-04-17T07:41:50.569+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:41:50.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:41:50.578+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:41:50.577+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:41:51.579+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:41:51.928+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:41:51.928+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:41:51.955+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:41:51.955+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:41:51.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.429 seconds
[2024-04-17T07:41:54.664+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:41:54.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:41:54.667+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:41:54.667+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:41:55.321+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:41:55.333+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:41:55.333+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:41:55.356+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:41:55.356+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:41:55.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.728 seconds
[2024-04-17T07:42:00.104+0000] {processor.py:161} INFO - Started process (PID=253) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:42:00.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:42:00.109+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:42:00.108+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:42:00.866+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:42:00.881+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:42:00.880+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:42:00.912+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:42:00.911+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:42:00.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.851 seconds
[2024-04-17T07:42:31.157+0000] {processor.py:161} INFO - Started process (PID=263) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:42:31.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:42:31.161+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:42:31.161+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:42:31.698+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:42:31.708+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:42:31.708+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:42:31.728+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:42:31.728+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:42:31.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.605 seconds
[2024-04-17T07:43:02.445+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:43:02.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:43:02.449+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:43:02.449+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:43:03.006+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:43:03.117+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:43:03.116+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:43:03.139+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:43:03.139+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:43:03.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.728 seconds
[2024-04-17T07:43:33.878+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:43:33.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:43:33.882+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:43:33.882+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:43:35.263+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:43:35.288+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:43:35.288+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:43:35.320+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:43:35.320+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:43:35.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.505 seconds
[2024-04-17T07:44:05.668+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:44:05.670+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:44:05.672+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:44:05.672+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:44:06.405+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:44:06.421+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:44:06.421+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:44:06.448+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:44:06.448+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:44:06.476+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.821 seconds
[2024-04-17T07:44:36.839+0000] {processor.py:161} INFO - Started process (PID=300) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:44:36.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:44:36.843+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:44:36.842+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:44:37.390+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:44:37.520+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:44:37.519+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:44:37.543+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:44:37.543+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:44:37.567+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.736 seconds
[2024-04-17T07:45:08.238+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:45:08.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:45:08.241+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:45:08.241+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:45:08.849+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:45:08.873+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:45:08.872+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:45:08.894+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:45:08.894+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:45:08.913+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.682 seconds
[2024-04-17T07:45:39.644+0000] {processor.py:161} INFO - Started process (PID=318) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:45:39.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:45:39.648+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:45:39.647+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:45:40.178+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:45:40.190+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:45:40.189+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:45:40.211+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:45:40.210+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:45:40.232+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.595 seconds
[2024-04-17T07:46:10.315+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:10.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:46:10.319+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:10.318+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:10.887+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:11.024+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:11.024+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:46:11.053+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:11.053+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:46:11.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.777 seconds
[2024-04-17T07:46:11.334+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:11.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:46:11.337+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:11.337+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:11.990+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:12.002+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:12.002+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:46:12.024+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:12.023+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:46:12.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.727 seconds
[2024-04-17T07:46:19.166+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:19.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:46:19.171+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:19.170+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:19.790+0000] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:19.802+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:19.801+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:46:19.825+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:19.824+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_world to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:46:19.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.698 seconds
[2024-04-17T07:46:28.506+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:28.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:46:28.512+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:28.512+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:29.120+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:29.238+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:29.237+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:sales_fact
[2024-04-17T07:46:29.249+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:29.249+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:sales_fact
[2024-04-17T07:46:29.260+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:29.259+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:sales_fact
[2024-04-17T07:46:29.261+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:29.260+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:46:29.272+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:29.272+0000] {dag.py:3118} INFO - Creating ORM DAG for sales_fact
[2024-04-17T07:46:29.285+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:29.284+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:46:29.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.818 seconds
[2024-04-17T07:46:34.393+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:34.394+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:46:34.396+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:34.395+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:34.966+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:34.978+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:34.977+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:46:35.000+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:34.999+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:46:35.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.645 seconds
[2024-04-17T07:46:37.575+0000] {processor.py:161} INFO - Started process (PID=344) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:37.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:46:37.578+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:37.578+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:38.196+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:46:38.186+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 47, in <module>
    default_args=default_args,
                 ^^^^^^^^^^^^
NameError: name 'default_args' is not defined
[2024-04-17T07:46:38.204+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:46:38.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.655 seconds
[2024-04-17T07:47:08.536+0000] {processor.py:161} INFO - Started process (PID=353) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:47:08.538+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:47:08.541+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:47:08.540+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:47:10.307+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:47:10.294+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/sales_fact.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_fact.py", line 47, in <module>
    default_args=default_args,
                 ^^^^^^^^^^^^
NameError: name 'default_args' is not defined
[2024-04-17T07:47:10.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:47:10.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.830 seconds
[2024-04-17T07:47:31.183+0000] {processor.py:161} INFO - Started process (PID=361) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:47:31.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:47:31.187+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:47:31.186+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:47:32.159+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:47:32.216+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:47:32.215+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:47:32.244+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:47:32.244+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-17T07:47:32.278+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.104 seconds
[2024-04-17T07:48:02.574+0000] {processor.py:161} INFO - Started process (PID=370) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:48:02.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:48:02.577+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:48:02.577+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:48:03.712+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:48:04.113+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:48:04.098+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:48:04.366+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:48:04.354+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T07:48:04.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.984 seconds
[2024-04-17T07:48:34.825+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:48:34.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:48:34.831+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:48:34.830+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:48:35.901+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:48:35.969+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:48:35.969+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:48:35.992+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:48:35.992+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T07:48:36.022+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.207 seconds
[2024-04-17T07:49:06.182+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:49:06.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:49:06.188+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:49:06.186+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:49:07.226+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:49:07.301+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:49:07.299+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:49:07.325+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:49:07.324+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T07:49:07.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.175 seconds
[2024-04-17T07:49:14.476+0000] {processor.py:161} INFO - Started process (PID=391) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:49:14.478+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:49:14.480+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:49:14.480+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:49:15.406+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:49:15.501+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:49:15.496+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:49:15.535+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:49:15.535+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T07:49:15.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.104 seconds
[2024-04-17T07:49:27.903+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:49:27.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:49:27.909+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:49:27.906+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:49:29.047+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:49:29.127+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:49:29.126+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:49:29.158+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:49:29.158+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T07:49:29.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.301 seconds
[2024-04-17T07:59:53.582+0000] {processor.py:161} INFO - Started process (PID=402) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:59:53.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:59:53.591+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:59:53.585+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:59:54.043+0000] {processor.py:161} INFO - Started process (PID=404) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T07:59:54.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T07:59:54.049+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:59:54.048+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:59:55.379+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T07:59:55.406+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:59:55.405+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'sales_fact', 'Task Id': 'sales_fact', 'Run Id': 'manual__2024-04-17T07:49:35.724301+00:00', 'Hostname': 'bfeb90cb790e', 'External Executor Id': 'eefb6f4f-962b-4de9-a285-1c793107260c'}
[2024-04-17T07:59:55.430+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:59:55.430+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sales_fact, task_id=sales_fact, execution_date=20240417T074935, start_date=20240417T074938, end_date=20240417T075955
[2024-04-17T07:59:55.440+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: sales_fact.sales_fact manual__2024-04-17T07:49:35.724301+00:00 [failed]> in state failed
[2024-04-17T07:59:55.473+0000] {logging_mixin.py:188} INFO - [2024-04-17T07:59:55.473+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T07:59:55.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.479 seconds
[2024-04-17T08:00:26.345+0000] {processor.py:161} INFO - Started process (PID=413) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T08:00:26.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T08:00:26.349+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:00:26.349+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:00:27.394+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:00:27.502+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:00:27.497+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T08:00:27.536+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:00:27.536+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T08:00:27.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.227 seconds
[2024-04-17T08:00:57.985+0000] {processor.py:161} INFO - Started process (PID=422) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T08:00:57.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T08:00:57.989+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:00:57.988+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:00:59.046+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:00:59.099+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:00:59.099+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T08:00:59.129+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:00:59.129+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T08:00:59.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.185 seconds
[2024-04-17T08:01:29.986+0000] {processor.py:161} INFO - Started process (PID=432) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T08:01:29.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T08:01:29.990+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:01:29.989+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:01:31.122+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:01:31.154+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:01:31.153+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T08:01:31.177+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:01:31.177+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T08:01:31.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.220 seconds
[2024-04-17T08:02:01.539+0000] {processor.py:161} INFO - Started process (PID=441) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T08:02:01.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T08:02:01.544+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:02:01.543+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:02:02.673+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:02:02.719+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:02:02.718+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T08:02:02.742+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:02:02.742+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T08:02:02.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.238 seconds
[2024-04-17T08:02:33.090+0000] {processor.py:161} INFO - Started process (PID=450) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T08:02:33.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T08:02:33.094+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:02:33.093+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:02:33.832+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:02:33.923+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:02:33.922+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T08:02:33.947+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:02:33.947+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T08:02:33.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 0.886 seconds
[2024-04-17T08:03:04.374+0000] {processor.py:161} INFO - Started process (PID=459) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T08:03:04.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T08:03:04.377+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:03:04.377+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:03:05.355+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:03:05.414+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:03:05.413+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T08:03:05.443+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:03:05.443+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T08:03:05.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.104 seconds
[2024-04-17T08:03:35.761+0000] {processor.py:161} INFO - Started process (PID=468) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T08:03:35.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T08:03:35.765+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:03:35.764+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:03:36.750+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:03:36.779+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:03:36.778+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T08:03:36.812+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:03:36.812+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T08:03:36.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.086 seconds
[2024-04-17T08:04:07.174+0000] {processor.py:161} INFO - Started process (PID=477) to work on /opt/airflow/dags/sales_fact.py
[2024-04-17T08:04:07.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_fact.py for tasks to queue
[2024-04-17T08:04:07.177+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:04:07.177+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:04:08.094+0000] {processor.py:840} INFO - DAG(s) 'sales_fact' retrieved from /opt/airflow/dags/sales_fact.py
[2024-04-17T08:04:08.148+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:04:08.147+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T08:04:08.178+0000] {logging_mixin.py:188} INFO - [2024-04-17T08:04:08.177+0000] {dag.py:3954} INFO - Setting next_dagrun for sales_fact to 2024-04-17 00:00:00+00:00, run_after=2024-04-18 00:00:00+00:00
[2024-04-17T08:04:08.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_fact.py took 1.033 seconds
